### ISSUE TITLE
Prioritize res:// completions

### ISSUE THREAD

**Issue by exigow** [exigow/intellij-gdscript#23]
Nested files should be less important than files in same directory. Prioritize by "distance" between files.

**Comment by dkantereivin** [comment]
In addition to this, please add support for single quotes to be recognized as res strings, currently only double quotes feature auto-completion and recognition as resource strings.

Over the weekend I will look through your source code and I may do a PR.

**Comment by exigow** [comment]
Hi,
thanks for your comment.

I've fixed single-quoted resources on the master branch (+ some other bugs).
Fix has not yet been uploaded to the JetBrains plugin hub, so if you want
to test, please let me know if everything is OK.

I've added tests for this case so the problem should not happen again.

Thanks and sorry for late response,
Jakub


pt., 5 cze 2020 o 11:33 D. Kanter <notifications@github.com> napisał(a):

**Comment by exigow** [comment]
Not important. Completions are sorted by file type, i think this is enough for now.
