### ISSUE TITLE
Good code red: dictionary with enum in keys

### ISSUE THREAD

**Issue by mnn** [exigow/intellij-gdscript#32]
<img width="177" alt="2020-01-24_11-48" src="https://user-images.githubusercontent.com/1975567/73063625-8167b100-3e9f-11ea-8c9e-868653bb4106.png">

Errors reported for squiggly lines:
> missing '(' at '.'
> mismatched input ':' expecting '('
> extraneous input ',' expecting {<EOF>, ';', ':', ''}

The code:
```python
const COOLDOWNS:= {
	T.CooldownType.BOMB_TOUCH: 1.0,
	T.CooldownType.BOMB_TIMER: 1.5,
	T.CooldownType.ATTACK_SMASH: 0.5
}
```
`T` is singleton autoloaded class, `CooldownType` is enum.

It's a first error in file, so I hope it's caused by the code I posted. The code is fine when viewed in script editor in Godot and works as intended.

**Comment by exigow** [comment]
@mnn, thank you for opening this issue! 

Fix is on current master. I modified the parser to allow expressions in entry keys. Your code should no longer be interpreted as an error.
