### ISSUE TITLE
Good code red: multiline statements

### ISSUE THREAD

**Issue by mnn** [exigow/intellij-gdscript#34]
```py
	var f_bool_cases = \
	[ [true, "true"]
	, [false, "false"]
	]
```

`\` is red and reports: `mismatched input '\' expecting {'~', '!', NODE, 'not', 'self', 'null', 'true', 'false', 'bool', 'int', 'float', 'void', CONSTANT, FUNCTION, '-', '.', '(', '[', '{', NUMBER, IDENTIFIER, RESOURCE, STRING_MULTILINE, STRING_DOUBLE_QUOTE, STRING_APHOSTROPHE}`

The code works and no issues are shown in Godot script editor.

**Comment by exigow** [comment]
More details: https://github.com/godotengine/godot/issues/208

**Comment by exigow** [comment]
@mnn, `\` characters are for now treated as whitespace. This is a fairly broad and incorrect assumption (*real* escaping does not work), but this solves your issue. I added a test with your sample so it shouldn't break anymore.
