### ISSUE TITLE
Correctly handle match patterns

### ISSUE THREAD

**Issue by Witik** [exigow/intellij-gdscript#50]
The [3.2 gdscript documentation](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#match) defines 7 types of match patterns.

This plugin does not handle all defined patterns correctly:
![constant-pattern](https://user-images.githubusercontent.com/1099130/81609303-f53eb280-93d7-11ea-80d1-3b9c417f1351.png)

![variable-pattern](https://user-images.githubusercontent.com/1099130/81609326-fe2f8400-93d7-11ea-96fe-8dbf66742d65.png)

![wildcard-pattern](https://user-images.githubusercontent.com/1099130/81609357-0982af80-93d8-11ea-9a5c-ca8ff8a907e1.png)

![array-pattern](https://user-images.githubusercontent.com/1099130/81609423-29b26e80-93d8-11ea-950e-e26ea3d2f619.png)

![dictionary-pattern](https://user-images.githubusercontent.com/1099130/81609451-3636c700-93d8-11ea-920b-a312342e588b.png)

![multiple-patterns](https://user-images.githubusercontent.com/1099130/81609470-3fc02f00-93d8-11ea-9f8e-ccb79ed1f462.png)

It looks as though the plugin only accepts constants as patterns

**Comment by exigow** [comment]
Thanks for examples. Looks like `var` statement is also expression.

**Comment by exigow** [comment]
@Witik, bug is fixed on master branch (#54). I added tests based on your examples so these false-negatives are unlikely to happen again in the future.
