### ISSUE TITLE
Trailing whitespace breaks the statement scope

### ISSUE THREAD

**Issue by mewore** [exigow/intellij-gdscript#72]
Steps to reproduce:
1. Write two statements
2. Add a trailing space at the end of the first statement

Result: The first statement and the second statement are merged. Any statements before the first one or the second one are still correctly left as separate statements.

Example:
![Screenshot at 2020-12-25 18-50-17](https://user-images.githubusercontent.com/46766863/103139164-31fab800-46e2-11eb-9915-cafb55cce46c.png)

This doesn't have any visible effects to the user for now, but it does cause some bugs down the line. For example, I found it when I added an error message for anything added after `class_name <identifier>` in the same statement and noticed there was an error for the whole next line when I added a trailing space after the `class_name` statement, which should actually be valid GDScript.

**Comment by chunchuna** [comment]
Is your LSP functioning properly?

**Comment by exigow** [comment]
@mewore, parser has been completely rewritten in version 0.34 and this issue should be fixed.

Related PR is here: https://github.com/exigow/intellij-gdscript/pull/82#issuecomment-962443842

This is still beta and awaiting verification, but you can check out the new implementation if you want. The feedback would be very valuable.

**Comment by exigow** [comment]
@mewore, merged to master. New version should be available soon.
