### ISSUE TITLE
Video Walkthrough Request

### ISSUE THREAD

**Issue by attishno1** [exigow/intellij-gdscript#81]
Hello! Thank you for viewing!

Instructions are not clear for a new user. I am using Rider. Please explain how can I use this as the Plugin is not working at all with no autocompletion and I do not know how to attach Rider to the language server.

A video walkthrough of connecting it is requested.

**Comment by exigow** [comment]
@attishno1, LSP was recently removed because it was very unstable and needed to be rewritten from scratch (see: 6d3ca27). Please note that this plugin still provides context-free autocomplete.
